type User @table {
  email: String!
  passwordHash: String!
  createdAt: Timestamp!
  firstName: String
  lastName: String
  shippingAddress: String
  billingAddress: String
}

type Product @table {
  name: String!
  price: Float!
  description: String!
  createdAt: Timestamp!
  imageUrl: String
  category: String
  stockQuantity: Int
}

type Order @table {
  user: User!
  orderDate: Timestamp!
  totalAmount: Float!
  status: String!
  createdAt: Timestamp!
  shippingAddressSnapshot: String
}

type OrderItem @table {
  order: Order!
  product: Product!
  quantity: Int!
  priceAtTimeOfOrder: Float!
  createdAt: Timestamp!
}

type Cart @table {
  user: User!
  createdAt: Timestamp!
  updatedAt: Timestamp!
}

type CartItem @table {
  cart: Cart!
  product: Product!
  quantity: Int!
  createdAt: Timestamp!
  updatedAt: Timestamp!
}